version: '3.1'

services:

  mariadb:
    image: timtrice/web:mariadb # mariadb:10.3.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qNlr0rZtf5VfGQ9m
    volumes:
      - web_mariadb:/var/lib/mysql

  mysql:
    image: timtrice/web:mysql # mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: e99rntuUXMGHB6Zt
    volumes:
      - web_mysql:/var/lib/mysql

  postgres:
    image: timtrice/web:postgres # postgres:9.6.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 5aJhjS7g7SAzE56K
    volumes:
      - web_postgres:/var/lib/postgresql/data

  rstudio:
    image: timtrice/datasets:rstudio_3.4.2 # rocker/rstudio:3.4.2
    volumes:
      - .:/home/rstudio/datasets
      - ../.Renviron:/home/rstudio/.Renviron
    ports:
      - "8787:8787"
    depends_on:
      - mariadb
      - mysql
      - postgres

volumes:
  web_mariadb:
    external: true
  web_mysql:
    external: true
  web_postgres:
    external: true
